services:
  db:
    image: mariadb:10.3.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
